#ifndef LIMITER_RESTRUCTION_H
#define LIMITER_RESTRUCTION_H

#include "defineGlobalVariable.h"

// WENORestruction GL:Gauss-Lobatto points
REAL WENOGL41(REAL, REAL, REAL, REAL, REAL);

REAL WENOGL42(REAL, REAL, REAL, REAL, REAL);

REAL WENOGL43(REAL, REAL, REAL, REAL, REAL);

REAL WENOGL44(REAL, REAL, REAL, REAL, REAL);

// WENORestruction PW
REAL WENOPW44(REAL, REAL, REAL, REAL, REAL);

REAL WENOPW41(REAL, REAL, REAL, REAL, REAL);

// ENORestruction
REAL ENO4UR(REAL, REAL, REAL, REAL, REAL, REAL, REAL);

REAL ENO4UL(REAL, REAL, REAL, REAL, REAL, REAL, REAL);

// 2-order
REAL Minmod(REAL a, REAL b);


#endif